import 'dart:math';

class SmartPasswordGenerator {
  static final _random = Random.secure();

  // Expanded dictionary containing short root words (4-5 letters) for massive entropy combinations
  static final List<String> _dictionary = [
    'acid',
    'apex',
    'aqua',
    'arch',
    'atom',
    'axis',
    'bark',
    'beam',
    'beta',
    'bird',
    'bolt',
    'bone',
    'boss',
    'bulb',
    'calm',
    'camp',
    'cave',
    'chef',
    'clay',
    'cliff',
    'code',
    'coin',
    'crew',
    'cube',
    'dawn',
    'desk',
    'dial',
    'disk',
    'dome',
    'dove',
    'duke',
    'dusk',
    'echo',
    'edge',
    'envoy',
    'epic',
    'exam',
    'exit',
    'face',
    'fact',
    'fair',
    'fame',
    'fang',
    'farm',
    'fate',
    'find',
    'fire',
    'fish',
    'flag',
    'flow',
    'flux',
    'foam',
    'font',
    'fuel',
    'fuse',
    'gala',
    'game',
    'gear',
    'gem',
    'glow',
    'gold',
    'grid',
    'gulf',
    'halo',
    'hawk',
    'haze',
    'hero',
    'hint',
    'hive',
    'icon',
    'idea',
    'iris',
    'iron',
    'item',
    'jade',
    'jazz',
    'join',
    'jolt',
    'judge',
    'jump',
    'keen',
    'kelp',
    'king',
    'kite',
    'lava',
    'leaf',
    'lens',
    'lime',
    'link',
    'lion',
    'lock',
    'loft',
    'logo',
    'loop',
    'lunar',
    'lynx',
    'maze',
    'mesh',
    'mind',
    'mint',
    'mode',
    'monk',
    'moss',
    'myth',
    'neon',
    'nest',
    'node',
    'nova',
    'oasis',
    'oat',
    'opal',
    'orbit',
    'oxford',
    'pace',
    'pack',
    'page',
    'palm',
    'path',
    'peak',
    'pearl',
    'plot',
    'plug',
    'poem',
    'poet',
    'polar',
    'pond',
    'pool',
    'port',
    'pulsar',
    'puma',
    'quad',
    'quantum',
    'quiz',
    'race',
    'raft',
    'rail',
    'rain',
    'ramp',
    'reef',
    'rift',
    'ring',
    'risk',
    'rock',
    'roof',
    'root',
    'rose',
    'ruby',
    'rush',
    'safe',
    'sage',
    'sail',
    'sand',
    'scale',
    'scout',
    'seal',
    'seed',
    'seek',
    'setup',
    'ship',
    'shoe',
    'sign',
    'silk',
    'silo',
    'site',
    'size',
    'skate',
    'skip',
    'sky',
    'snow',
    'soap',
    'sofa',
    'solar',
    'song',
    'soul',
    'spark',
    'spin',
    'spur',
    'star',
    'step',
    'surf',
    'swan',
    'tack',
    'tact',
    'tail',
    'tank',
    'tape',
    'team',
    'tent',
    'text',
    'thaw',
    'tide',
    'tiger',
    'tilt',
    'time',
    'tint',
    'toad',
    'toll',
    'tone',
    'top',
    'tour',
    'town',
    'toxic',
    'trace',
    'track',
    'trade',
    'trail',
    'train',
    'tramp',
    'trap',
    'tray',
    'tree',
    'trek',
    'trend',
    'trial',
    'tribe',
    'trick',
    'trio',
    'trip',
    'trophy',
    'trout',
    'tube',
    'tuck',
    'tuft',
    'tulip',
    'tuna',
    'tune',
    'tunnel',
    'turf',
    'turn',
    'tusk',
    'tutor',
    'twin',
    'twist',
    'type',
    'unify',
    'unit',
    'unity',
    'urge',
    'urn',
    'user',
    'vale',
    'valve',
    'vapor',
    'vase',
    'vault',
    'vector',
    'veil',
    'vein',
    'velvet',
    'vent',
    'verb',
    'vertex',
    'vessel',
    'vest',
    'vial',
    'vibe',
    'video',
    'view',
    'vine',
    'vinyl',
    'viola',
    'viper',
    'viral',
    'virus',
    'visit',
    'visor',
    'vista',
    'vivid',
    'vocal',
    'vodka',
    'vogue',
    'voice',
    'void',
    'volcano',
    'volt',
    'vortex',
    'vote',
    'vowel',
    'voyage',
    'vulcan',
    'wade',
    'wafer',
    'waffle',
    'wagon',
    'waist',
    'wait',
    'waive',
    'wake',
    'walk',
    'wall',
    'walnut',
    'wand',
    'want',
    'ward',
    'warm',
    'warn',
    'warp',
    'wart',
    'wash',
    'wasp',
    'waste',
    'watch',
    'water',
    'wave',
    'wavy',
    'wax',
    'web',
    'wedge',
    'weed',
    'week',
    'weep',
    'weigh',
    'weld',
    'well',
    'west',
    'whale',
    'wharf',
    'wheat',
    'wheel',
    'while',
    'whip',
    'whirl',
    'whisk',
    'whisper',
    'white',
    'whole',
    'wick',
    'wide',
    'widow',
    'width',
    'wield',
    'wife',
    'wild',
    'willow',
    'wind',
    'window',
    'windy',
    'wine',
    'wing',
    'wink',
    'winner',
    'winter',
    'wipe',
    'wire',
    'wiry',
    'wisdom',
    'wise',
    'wish',
    'witch',
    'witty',
    'wizard',
    'wolf',
    'woman',
    'wombat',
    'wonder',
    'wood',
    'wool',
    'word',
    'work',
    'world',
    'worm',
    'worry',
    'worse',
    'worst',
    'worth',
    'wound',
    'woven',
    'wrap',
    'wreck',
    'wren',
    'wrench',
    'wrestle',
    'wring',
    'wrist',
    'write',
    'wrong',
    'yacht',
    'yard',
    'yarn',
    'yawn',
    'year',
    'yeast',
    'yell',
    'yellow',
    'yeti',
    'yield',
    'yoga',
    'yogurt',
    'yoke',
    'yolk',
    'young',
    'youth',
    'zebra',
    'zenith',
    'zero',
    'zest',
    'zigzag',
    'zinc',
    'zipper',
    'zone',
  ];

  static final Map<String, String> _leetMapping = {
    'i': '!',
    'I': '!',
    'a': '@',
    'A': '@',
    'o': '0',
    'O': '0',
    's': '\$',
    'S': '\$',
    'e': '3',
    'E': '3',
    't': '7',
    'T': '7',
  };

  static final List<String> _specialChars = [
    '!',
    '@',
    '#',
    '\$',
    '%',
    '&',
    '*',
  ];

  /// Generates a password structurally constrained strictly between 8 and 12 characters.
  static String generate() {
    // 1. Grab a random word from our expanded dictionary array context
    String rawWord = _dictionary[_random.nextInt(_dictionary.length)];

    // 2. Ensure length compatibility (truncate raw word if it accidentally exceeds 6 characters)
    if (rawWord.length > 6) {
      rawWord = rawWord.substring(0, 6);
    }

    // 3. Apply standard Title Case layout configuration
    String processedWord =
        rawWord.substring(0, 1).toUpperCase() +
        rawWord.substring(1).toLowerCase();

    // 4. Run the intelligent look-alike character substitution script
    String leetWord = _applyLeetSpeak(processedWord);

    // 5. Calculate remaining space dynamically to stay within the 8-12 ceiling budget
    // Minimum target: 8 characters total. Maximum ceiling target: 12 characters total.
    int currentLength = leetWord.length; // usually 3 to 6 chars
    int targetPaddingLength = (10 - currentLength).clamp(
      3,
      5,
    ); // Target total ~10 characters

    // 6. Generate precise numeric trailing components
    int minNum = pow(10, targetPaddingLength - 2).toInt();
    int maxNum = (pow(10, targetPaddingLength - 1) - 1).toInt();
    int digitsBlock = minNum + _random.nextInt(maxNum - minNum);

    // 7. Extract structural symbol wrapping anchor
    String specialChar = _specialChars[_random.nextInt(_specialChars.length)];

    // 8. Composite assembly bundle layout
    String finalPassword = '$leetWord$specialChar$digitsBlock';

    // Emergency truncation fail-safe guard boundary rule
    if (finalPassword.length > 12) {
      finalPassword = finalPassword.substring(0, 12);
    }

    return finalPassword;
  }

  static String _applyLeetSpeak(String input) {
    final buffer = StringBuffer();
    for (int i = 0; i < input.length; i++) {
      final char = input[i];
      buffer.write(_leetMapping[char] ?? char);
    }
    return buffer.toString();
  }
}
