import 'dart:async';
import 'package:pwm/features/secrets/domain/entities/secret_entity.dart';
import 'package:pwm/features/secrets/domain/usecases/delete_secret_usecase.dart';
import 'package:pwm/features/secrets/domain/usecases/get_secrets_usecase.dart';
import 'package:pwm/features/secrets/domain/usecases/save_secret_usecase.dart';
import 'package:pwm/features/secrets/domain/usecases/update_secret_usecase.dart';
import 'package:pwm/features/secrets/presentation/managers/secret_events.dart';
import 'package:pwm/features/secrets/presentation/managers/secret_states.dart';
import 'package:rxdart/rxdart.dart';

class SecretVM {
  final GetSecretsUsecase getSecretsUsecase;
  final SaveSecretUsecase saveSecretUsecase;
  final DeleteSecretUsecase deleteSecretUsecase;
  final UpdateSecretUsecase updateSecretUsecase;

  // events will be generated by the ui
  final _secretEventSubject = ReplaySubject<SecretEvent>();
  StreamSink<SecretEvent> get updateSecretEvent => _secretEventSubject.sink;

  // states listed in UI
  final _secretStateSubject = BehaviorSubject<SecretState>.seeded(
    SecretInitialState(),
  );
  ValueStream<SecretState> get secretState$ => _secretStateSubject.stream;

  // data for hydration
  final _secretsSubject = BehaviorSubject<List<SecretEntity>>.seeded([]);
  ValueStream<List<SecretEntity>> get secrets$ => _secretsSubject.stream;

  late final StreamSubscription _secretEventSubscription;

  SecretVM({
    required this.getSecretsUsecase,
    required this.saveSecretUsecase,
    required this.deleteSecretUsecase,
    required this.updateSecretUsecase,
  }) {
    _secretEventSubscription = _secretEventSubject.listen(_mapEventsToStates);
  }

  void _mapEventsToStates(SecretEvent event) async {
    if (event is GetAllSecretsEvent) {
      _secretStateSubject.add(SecretLoadingState());
      final secrets = await getSecretsUsecase();
      _secretsSubject.add(secrets);
      _secretStateSubject.add(SecretDirtyState());
    } else if (event is AddSecretEvent) {
      _secretStateSubject.add(SecretLoadingState());
      await saveSecretUsecase(event.newSecret);
      final secrets = await getSecretsUsecase();
      _secretsSubject.add(secrets);
      _secretStateSubject.add(SecretDirtyState());
    } else if (event is UpdateSecretEvent) {
      _secretStateSubject.add(SecretLoadingState());
      await updateSecretUsecase(event.updatedSecret);
      final secrets = await getSecretsUsecase();
      _secretsSubject.add(secrets);
      _secretStateSubject.add(SecretDirtyState());
    } else if (event is DeleteSecretEvent) {
      _secretStateSubject.add(SecretLoadingState());
      await deleteSecretUsecase(event.deleteId);
      final secrets = await getSecretsUsecase();
      _secretsSubject.add(secrets);
      _secretStateSubject.add(SecretDirtyState());
    }
  }

  void dispose() {
    _secretEventSubscription.cancel();
    _secretEventSubject.close();
    _secretStateSubject.close();
    _secretsSubject.close();
  }
}
